#!/usr/bin/python3

import math
import sys

def pollard_rho_factoring(n):
    if n % 2 == 0:
        return 2
    
    x = 2
    d = 1
    
    f = lambda x: (x**2 + 1) % n
    
    while d == 1:
        d = math.gcd(abs(f(x) - f(f(x))), n)
    
    return d



def main():
    if len(sys.argv) != 2:
        print("Usage: python factors.py <file>")
        return

    file_path = sys.argv[1]

    try:
        with open(file_path, 'r') as file:
            numbers = file.readlines()
        for number in numbers:
            num = int(number.strip())
            factor = pollard_rho_factoring(num)
            if factor == num:
                print(f"{num} is prime.")
            else:
                print(f"{num}={num // factor}*{factor}")
    except FileNotFoundError:
        print(f"File '{file_path}' not found.")

if __name__ == '__main__':
    main()
