#!/usr/bin/env bash

factorize() {
    num=$1
    for (( divisor = 2; divisor * divisor <= num; divisor++ )); do
        while (( num % divisor == 0 )); do
            factors+=("$divisor")
            num=$(( num / divisor ))
        done
    done

    if (( num > 1 )); then
        factors+=("$num")
    fi
}

if [ $# -ne 1 ]; then
    echo 'Usage: rsa <file>'
    exit 1
fi

while read -r line; do
    factors=()
    factorize "$line"
    n=${factors[0]}
    m=${factors[1]}
    
    if [ -z "$m" ]; then
        echo "$line is prime."
    else
        echo "$line=$n*$m"
    fi
done < "$1"

